export const popularni = [
    { id: 1, title: "Ave Maria – J.Smolík" },
    { id: 2, title: "Ave Maria – L.Bílá" },
    { id: 3, title: "Ave Maria – Š.Margita" },
    { id: 4, title: "Až mě andělé – P.Spálený (vhodné pro muže)" },
    { id: 5, title: "Bílá orchidej – Eva a Vašek" },
    { id: 6, title: "Buď pořád se mnou – W. Matuška" },
    { id: 7, title: "Cesta poslední – K.Černoch" },
    { id: 8, title: "Čekej tiše – E.Olmerová" },
    { id: 9, title: "Díky za všechno, mámo – J.Schelinger" },
    { id: 10, title: "Haleluja – J.Smolík" },
    { id: 11, title: "Holubí dům – J.Schelinger" },
    { id: 12, title: "Hospůdko známá – Eva a Vašek / J. Mayer" },
    { id: 13, title: "Chlap, co tady chybí – Roháči" },
    { id: 14, title: "Indiánská píseň lásky – F.Slováček" },
    { id: 15, title: "Já budu žít navěky – M.Tučný" },
    { id: 16, title: "Já se vrátím – K.Gott" },
    { id: 17, title: "Jednoho dne se vrátíš – V.Špinarová" },
    { id: 18, title: "Jednou je hůř, jednou je líp – J.Korn" },
    { id: 19, title: "Karavana mraků – K.Kryl" },
    { id: 20, title: "Kdyby sis oči vyplakala – K.Gott" },
    { id: 21, title: "Když andělé pláčou – J.Smolík" },
    { id: 22, title: "Když jsem já byl tenkrát kluk – K.Gott" },
    { id: 23, title: "Když mne stará matka – K.Gott" },
    { id: 24, title: "Kometa – J.Nohavica" },
    { id: 25, title: "Kvete růže, podívej – H.Vondráčková" },
    { id: 26, title: "Léta prázdnin – K.Gott" },
    { id: 27, title: "Loudá se půlměsíc – M. Kubišová" },
    { id: 28, title: "Máma – M.Rottrová" },
    { id: 29, title: "Maminka – J.Smolík" },
    { id: 30, title: "Maminko vrať se – L.Bílá" },
    { id: 31, title: "Mys dobrých nadějí – H.Zagorová" },
    { id: 32, title: "Nebe na zemi – J.Werich" },
    { id: 33, title: "Ó mámo – P. Rezek" },
    { id: 34, title: "Oči má sněhem zaváté – K.Gott" },
    { id: 35, title: "Otče můj – J.Zmožek" },
    { id: 36, title: "Pampelišky – Duo Červánky – country" },
    { id: 37, title: "Pro mámu – Holki" },
    { id: 38, title: "Sbohem lásko, nech mě jít – W.Matuška" },
    { id: 39, title: "Sen lásky – Y.Simonová" },
    { id: 40, title: "Slunečný hrob – Blue Effect / HRANÉ" },
    { id: 41, title: "Slunovrat – Brontosauři" },
    { id: 42, title: "Slyšíš jak zvoní – Šohajka" },
    { id: 43, title: "Svítá – Eva a Vašek" },
    { id: 44, title: "Tam na konci světa – H.Tomm, K.Fialová" },
    { id: 45, title: "Tam u nebeských bran – M.Tučný (pro muže)" },
    { id: 46, title: "Táto, já vím – G.Goldová" },
    { id: 47, title: "Tátovi – K.Gott" },
    { id: 48, title: "Tenkrát na západě - HRANÉ" },
    { id: 49, title: "Tisíckrát – Z.Jandová" },
    { id: 50, title: "Už z hor, zní zvon – K.Gott" },
    { id: 102, title: "Zbylo jen přání - Argema" },
    { id: 103, title: "Always – Bon Jovi" },
    { id: 104, title: "Bohemian Rhapsody – Queen" },
    { id: 105, title: "Can You Feel The Love Tonight – E.John" },
    { id: 106, title: "Candle In The Wind – E.John" },
    { id: 107, title: "Can’t Help Falling In Love – E. Presley" },
    { id: 108, title: "Carrie – Europe" },
    { id: 109, title: "Don't You Cry – Guns N' Roses" },
    { id: 110, title: "Dust In The Wind – Kansas" },
    { id: 111, title: "Hallelujah – L.Cohen" },
    { id: 112, title: "Imagine - J.Lennon" },
    { id: 113, title: "Knockin' On Heaven’s Door – Guns N' Roses" },
    { id: 114, title: "Love Hurts – Nazareth" },
    { id: 115, title: "Mon Dieu – E.Piaf" },
    { id: 116, title: "My Oh My – Slade" },
    { id: 117, title: "My Way – F.Sinatra" },
    { id: 118, title: "Non Je Ne Regrette Rien – E.Piaf" },
    { id: 119, title: "Nothing Else Matters - HRANÉ / Metallica" },
    { id: 120, title: "Ohne Dich – Rammstein" },
    { id: 121, title: "One More Light - Linkin Park" },
    { id: 122, title: "Only Time – Enya" },
    { id: 123, title: "Show Must Go On – Queen" },
    { id: 124, title: "Somewhere Over The Rainbow" },
    { id: 125, title: "Stand By Me – B.E. King" },
    { id: 126, title: "Still Loving You – Scorpions" },
    { id: 127, title: "Tears In Heaven – E. Clapton" },
    { id: 128, title: "The Way We Were – B. Streisand" },
    { id: 129, title: "Thought I'd Ring You – S.Basey, A.Delon" },
    { id: 130, title: "Time To Say Goodbye – A.Bocelli, S.Brightman" },
    { id: 131, title: "What A Wonderful World – L.Armstrong" },
    { id: 132, title: "Who Wants To Live Forever – Queen" },
    { id: 133, title: "Wind Of Change – Scorpions" }
  ];

  export const sportovni = [
    { id: 134, title: "Zpívej, kdo jsi sparťanem" },
    { id: 135, title: "Mám fotbal rád – K. Zich" },
    { id: 136, title: "Slávistická hymna" }
  ];

  export const vazna = [
    { id: 137, title: "Adagio A moll z viol. Konc. - R.Schumann" },
    { id: 138, title: "Air – J.S.Bach" },
    { id: 139, title: "Alžbětinská serenáda - R.Binge" },
    { id: 140, title: "Ave Maria – Bach – Gounod" },
    { id: 141, title: "Ave Maria – F.Schubert" },
    { id: 142, title: "Klavírní koncert b moll - P.I.Čajkovskij" },
    { id: 143, title: "Humoreska – P.Katin" },
    { id: 144, title: "Když mne stará matka – A.Dvořák" },
    { id: 145, title: "Labuť – C.Saint-Saëns" },
    { id: 146, title: "Largo – G.F.Händel" },
    { id: 147, title: "Largo z Novosvětské – A.Dvořák" },
    { id: 148, title: "Memory – Vzpomínka – K.Popper" },
    { id: 149, title: "Meeting Again – M. Richter" },
    { id: 150, title: "Nabucco - G.Verdi (Sbor židov. otroků)" },
    { id: 151, title: "Píseň beze slov – Mendelssohn-Bartholdy" },
    { id: 152, title: "Podzimní píseň – P.I.Čajkovskij" },
    { id: 153, title: "Poem - Z.Fibich" },
    { id: 51, title: "V příštím životě – K.Gott" },
    { id: 52, title: "Veď mě dál, cesto má – P.Bobek" },
    { id: 53, title: "Vincent – P.Bobek" },
    { id: 54, title: "Vltava – K. Gott" },
    { id: 55, title: "Vzdávám dík – Eva a Vašek" },
    { id: 56, title: "Závidím – N.Urbánková" },
    { id: 57, title: "Anděl – K. Kryl" },
    { id: 58, title: "Anděl – Mirai" },
    { id: 59, title: "Andělé – ATMO music, J. Děkan" },
    { id: 60, title: "Andělská – Z. Navarová" },
    { id: 61, title: "Až na vrcholky hor – V. Martinová" },
    { id: 62, title: "Boli sme raz milovaní – P. Habera" },
    { id: 63, title: "Bože můj já chci zpět – H. Hegerová" },
    { id: 64, title: "Bůh – Pekař" },
    { id: 65, title: "Černý páv – H. Zagorová" },
    { id: 66, title: "Dopis do nebe – J. Nedvěd" },
    { id: 67, title: "Děkuji – K. Kryl" },
    { id: 68, title: "Houby magický – Kabát" },
    { id: 69, title: "Hurikán – D. Janda" },
    { id: 70, title: "Jednou - Olympic" },
    { id: 71, title: "Jednu malou chvíli - L. Bílá a J. Bendig" },
    { id: 72, title: "Kde jsi – M. Rottrová" },
    { id: 73, title: "Kříž svůj neseme – J. Nohavica, P. Cmorik" },
    { id: 74, title: "Kým pri mne spíš – P. Habera" },
    { id: 75, title: "Letokruhy - TRAKTOR" },
    { id: 76, title: "Lítej – Mirai" },
    { id: 77, title: "Maluju na nebe – V. Nedvěd" },
    { id: 78, title: "Máma – M. David" },
    { id: 79, title: "Máma mi na krk dala klíč – J. Nohavica" },
    { id: 80, title: "Mami – T. Kerndlová" },
    { id: 81, title: "Modlitba pro duši – M. Pártlová" },
    { id: 82, title: "Morituri Te Salutant – K. Kryl" },
    { id: 83, title: "Můj rodný dům – P. Bobek" },
    { id: 84, title: "Nad stádem koní – Buty" },
    { id: 85, title: "Náhrobní kámen – P. Novák" },
    { id: 86, title: "Nesnáším loučení – M. David" },
    { id: 87, title: "Odcházím – Harlej" },
    { id: 88, title: "Otec a syn – J. Smolík, T. Vimr (rybářská)" },
    { id: 89, title: "Pár přátel stačí mít – M. David" },
    { id: 90, title: "Pie Jesu – L. Bílá" },
    { id: 91, title: "Podvod – J. Nedvěd" },
    { id: 92, title: "Pokoj v duši – J. Kirschner" },
    { id: 93, title: "Sen – Lucie" },
    { id: 94, title: "Síla starejch vín – Škwor" },
    { id: 95, title: "Slzy tvý mámy - Olympic" },
    { id: 96, title: "Tati – H. Navrátilová (akustická)" },
    { id: 97, title: "Touha a pláč – Jelen" },
    { id: 98, title: "Srdce nehasnou – K. Gott & Ch. E. Gottová" },
    { id: 99, title: "Stroj času – L. Bílá" },
    { id: 100, title: "Voda Živá – A. Langerová" },
    { id: 101, title: "Vzpomínka – A. Langerová" },
    { id: 154, title: "Ukolébavka – W.A.Mozart" },
    { id: 155, title: "Večerní píseň – R.Schumann" },
    { id: 156, title: "Vltava - B.Smetana" },
    { id: 157, title: "Vzpomínka – B.Smetana" },
    { id: 158, title: "A Gift Of A Thistle - J.Horner (Statečné srdce)" },
    { id: 159, title: "For The Love Of A Princess - J.Horner" },
    { id: 160, title: "Honor - H. Zimmer (The Pacific)" },
    { id: 161, title: "I Don't Want To Miss A Thing - Aerosmith" },
    { id: 162, title: "Le Professionnel - E. Morricone (Profesionál)" },
    { id: 163, title: "Murron's Burial - J. Horner (Statečné srdce)" },
    { id: 164, title: "My Heart Will Go On – C. Dion (Titanic)" },
    { id: 165, title: "Now We Are Free – H. Zimmer (Gladiator)" },
    { id: 166, title: "Tennessee - H. Zimmer (Pearl Harbor)" },
    { id: 167, title: "The Lonely Shepherd – G.Zamfir" },
    { id: 168, title: "The Funeral – E.Morricone" },
    { id: 169, title: "Time - H. Zimmer (Inception)" }
  ];

  export const lidove = [
    { id: 170, title: "Ach synku synku" },
    { id: 171, title: "Akáty bílé" },
    { id: 172, title: "Blíž Tobě Bože můj" },
    { id: 173, title: "Co jste hasiči, co jste dělali – ZPÍVANÉ/HRANÉ" },
    { id: 174, title: "Čechy krásné" },
    { id: 175, title: "Do lesíčka na čekanou" },
    { id: 176, title: "Dobrú noc má milá" },
    { id: 177, title: "Důvěřuj se v Pána" },
    { id: 178, title: "Ha ty sv. Vavřinečku – z Chodska" },
    { id: 179, title: "Bílé konvalinky - F.Soukup" },
    { id: 180, title: "Lásko, bože lásko" },
    { id: 181, title: "Loučení, loučení" },
    { id: 182, title: "Loučím se s Vámi kamarádi" },
    { id: 183, title: "Maminko, mámo" },
    { id: 184, title: "Moravo, Moravo" },
    { id: 185, title: "Můj táta rybářem byl" },
    { id: 186, title: "Nejsmutnější loučení je s mámou" },
    { id: 187, title: "Noc májová" },
    { id: 188, title: "Ó řebíčku zahradnický" },
    { id: 189, title: "Ó Velvary" },
    { id: 190, title: "Pod tou naší starou lípou" },
    { id: 191, title: "Rodné brázdy" },
    { id: 192, title: "Rožnovské hodiny" },
    { id: 193, title: "Široký, hluboký, ty Vltavský tůně" },
    { id: 194, title: "Ta naše písnička česká" },
    { id: 195, title: "Když se ten Tálinskej rybník nahání" },
    { id: 196, title: "Tam v krásné Šumavě" },
    { id: 197, title: "Tatíčku, starý náš" },
    { id: 198, title: "Teče voda, teče – K.Gott" },
    { id: 199, title: "Tichá noc, Svatá noc – K. Gott" },
    { id: 200, title: "U studánky seděla" },
    { id: 201, title: "Už mě koně vyvádějí – J. Černý" },
    { id: 202, title: "Valčík na rozloučenou" },
    { id: 203, title: "Vesničko má pod Šumavou" },
    { id: 204, title: "Zahučaly hory, zahučaly lesy" },
    { id: 205, title: "Zasviť mi ty slunko zlaté" },
    { id: 206, title: "Zelení hájové" }
  ];
  